version: '3.8'
services:
  fitfriends.postgres:
    image: postgres:14-alpine
    container_name: fitfriends.postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    ports:
      - 5432:5432
    volumes:
      - ~/db/fitfriends.postgres:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d fitfriends" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - fitfriends

  fitfriends.pgadmin:
    image: dpage/pgadmin4:7.3
    container_name: fitfriends.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "keks@htmlacademy.local"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8082:80
    networks:
      - fitfriends

volumes:
  fitfriends.postgres:

networks:
  fitfriends:
      driver: bridge
