# Get all user notification 
GET http://localhost:3333/api/notification HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJlbWFpbCI6InNlcDNvb2NsaWVudGllbnFxMjMyM292QGdtYWlsLmN3bSIsInVzZXJSb2xlIjoiY2xpZW50IiwibmFtZSI6ItCS0LDRgdC40LvQuNC5IiwiaWF0IjoxNjg5NjkwMTMxLCJleHAiOjE2ODk2OTEwMzF9.NI1Cl6X-xuPRVCZxZc-pbfIoqSNAqIsMNYGUKLXlpTo
###

#Create notification

POST http://localhost:3333/api/notification HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJlbWFpbCI6InNlcDRvb2NsaWVudGllbnFxMjMyM292QGdtYWlsLmN3bSIsInVzZXJSb2xlIjoidHJhaW5lciIsIm5hbWUiOiLQktCw0YHQuNC70LjQuSIsImlhdCI6MTY4OTY4OTk3MCwiZXhwIjoxNjg5NjkwODcwfQ.GAP0aElhOzz_7gIWojZ2kmB3x6WbnKHoCjRy9gr394Q
Content-Type: application/json

{
  "typesOfNotification": "добавить в друзья",
  "targetUserId": 16
}

### 

#Delete notification
DELETE http://localhost:3333/api/notification/2 HTTP/1.1 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE2LCJlbWFpbCI6InNlcDNvb2NsaWVudGllbnFxMjMyM292QGdtYWlsLmN3bSIsInVzZXJSb2xlIjoiY2xpZW50IiwibmFtZSI6ItCS0LDRgdC40LvQuNC5IiwiaWF0IjoxNjg5NjkwMTMxLCJleHAiOjE2ODk2OTEwMzF9.NI1Cl6X-xuPRVCZxZc-pbfIoqSNAqIsMNYGUKLXlpTo