# Create a new user
POST http://localhost:3333/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "userName": "Василий",
  "userMail": "sep4ooclientienqq2323ov@gmail.cwm",
  "userAvatar": "",
  "password": "adsfaasdfadf",
  "userGender": "мужской",
  "birthDate": "1955-11-06",
  "userRole": "client",
  "description": "trainertrainertrainertrainertrainer",
  "location": "Пионерская",
  "backgraundPicture": "asdf.jpg",
  "trainerBody": {
    "sertificate": "sert.pdf",
    "merit": "чтото напишем",
    "readinessForPrivate": true
  },
  "levelOfExperience": "профессионал",
  "typesOfTraining": ["стрейчинг", "кроссфит"]
}
###

# Update user 
PATCH http://localhost:3333/api/auth HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoic2VwM29vYWRkd3dxcTIzNDIxMjNvdkBnbWFpbC5jd20iLCJ1c2VyUm9sZSI6InRyYWluZXIiLCJuYW1lIjoi0JLQsNGB0LjQuzExMdC40LkiLCJpYXQiOjE2ODg2NTE3MTIsImV4cCI6MTY4ODY1MjYxMn0.1MKYMm_-qdzSyHhLQ5afagLnRxeancN3QPmiCwXdscs
Content-Type: application/json

{
  "userName": "Васил1www11ий",
  "userAvatar": ""
}

###

# Get user by ID
GET http://localhost:3333/api/auth/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6InNlcDNvb2NsaWVudGFsaWVucXEyMzIzb3ZAZ21haWwuY3dtIiwidXNlclJvbGUiOiJjbGllbnQiLCJuYW1lIjoi0JLQsNGB0LjQu9C40LkiLCJpYXQiOjE2ODg4MDc2ODMsImV4cCI6MTY4ODgwODU4M30.oeufk86eLs2CuIOVKhIRRC3hBLetzLoZwbuipVI-rTE
###

# Login user by email and password
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "sep4ooclientienqq2323ov@gmail.cwm",
  "password": "adsfaasdfadf"
}
###
# Get user  feed
GET http://localhost:3333/api/auth/feed?limit=4&page=1&userRole=trainer&locations=Пионерская,Петроградская&typesOfTraining=йога,кроссфит HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6InNlcDNvb2NsaWVudGFsaWVucXEyMzIzb3ZAZ21haWwuY3dtIiwidXNlclJvbGUiOiJjbGllbnQiLCJuYW1lIjoi0JLQsNGB0LjQu9C40LkiLCJpYXQiOjE2ODg4MDc2ODMsImV4cCI6MTY4ODgwODU4M30.oeufk86eLs2CuIOVKhIRRC3hBLetzLoZwbuipVI-rTE
###
# Get new JWT pair
POST http://localhost:3000/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDUyMDkzMDExYmI2MzU2NTk5OTdhYzIiLCJlbWFpbCI6InVzZXJAbmZmb29vby5sb2NhbCIsInJvbGUiOiJ1c2VyIiwibGFzdG5hbWUiOiJTbWl0aCIsImZpcnN0bmFtZSI6Iktla3MiLCJ0b2tlbklkIjoiOGY5Y2Q0YjEtOGEzNC00M2U2LWFmZjYtZDgwMGQyNTZhZDgyIiwiaWF0IjoxNjgzMTAzMDc1LCJleHAiOjE2ODU2OTUwNzV9.LPC7cm10NzP8jhKUzHSTc8zFFZHS8hbzcQZ7mIvGbas


###

# Check user token
GET http://localhost:3333/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN0ZXAzMWFud3dxcTIxMjNvdkBnbWFpbC5jb20iLCJ1c2VyUm9sZSI6InRyYWluZXIiLCJuYW1lIjoi0JLQsNGB0LjQu9C40LkiLCJpYXQiOjE2ODg0NTc3NTAsImV4cCI6MTY4ODQ1ODY1MH0.CrXuN3KU25h0mNyG54BhByc2_G7DrtQ3N2pHgDXvb2E


###