# Create a new user
POST http://localhost:3333/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "userName": "Василий",
  "userMail": "clienbbbdddt@gmail.cwm",
  "userAvatar": "",
  "password": "adsfaasdfadf",
  "userGender": "мужской",
  "birthDate": "1955-11-06",
  "userRole": "trainer",
  "description": "trainertrainertrainertrainertrainer",
  "location": "Пионерская",
  "backgraundPicture": "asdf.jpg",
  "trainerBody": {
    "sertificates": ["sert.pdf"],
    "merit": "чтото напишем",
    "readinessForPrivate": true
  },
  "levelOfExperience": "профессионал",
  "typesOfTraining": ["стрейчинг", "кроссфит"]
}
###

# Update user 
PATCH http://localhost:3333/api/auth/update HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYxLCJlbWFpbCI6ImNsaWVuYmJiZGRkdEBnbWFpbC5jd20iLCJ1c2VyUm9sZSI6InRyYWluZXIiLCJuYW1lIjoi0JLQsNGB0LjQu9C40LkiLCJpYXQiOjE2OTIxMTIwNDYsImV4cCI6MTY5MjExMjk0Nn0.f3TpcadhHt-WsQ53SIkI4X9Y6HXg57nIiOaBa_LURyM
Content-Type: application/json

{
  "trainerBody": {"merit": "что-то напишем про Машу"}
}

###

# Get user by ID
GET http://localhost:3333/api/auth/user/51 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYxLCJlbWFpbCI6ImNsaWVuYmJiZGRkdEBnbWFpbC5jd20iLCJ1c2VyUm9sZSI6InRyYWluZXIiLCJuYW1lIjoi0JLQsNGB0LjQu9C40LkiLCJpYXQiOjE2OTIxMTIwNDYsImV4cCI6MTY5MjExMjk0Nn0.f3TpcadhHt-WsQ53SIkI4X9Y6HXg57nIiOaBa_LURyM
###

# Login user by email and password
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "ivanTreiner@gmail.com",
  "password": "qwertyuiop"
}
###
# Get user  feed
GET http://localhost:3333/api/auth/feed?limit=4&page=1&userRole=trainer&locations=Пионерская,Петроградская&typesOfTraining=йога,кроссфит HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJlbWFpbCI6InNlcDRvb2NsaWVudGllbnFxMjMyM292QGdtYWlsLmN3bSIsInVzZXJSb2xlIjoidHJhaW5lciIsIm5hbWUiOiLQktCw0YHQuNC70LjQuSIsImlhdCI6MTY5MDk5NTQ5NCwiZXhwIjoxNjkwOTk2Mzk0fQ.iY9A0_SuParyBJfRt3EFe9YMCp8HLdqvaE-iqheleLA
###
# Get new JWT pair (refresh)
POST http://localhost:3333/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjY3LCJlbWFpbCI6ImNsaWVudG1hc2hhQGdtYWlsLmN3bSIsInVzZXJSb2xlIjoiY2xpZW50IiwibmFtZSI6Ik1hc2ggQ2xpZW50MSIsInRva2VuSWQiOiJjNGQ3M2NjYS01ODAxLTQ1ZmYtOTM4Ny05MTk3NGFkYmRiYWMiLCJpYXQiOjE3MDExNjMyMDYsImV4cCI6MTcwMzc1NTIwNn0.LuCSTAFRQqPfL_TRqV0fpcxZ7D8fe76Xs6cW8XZamhY


# Check user token
GET http://localhost:3333/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjY1LCJlbWFpbCI6Iml2YW5UcmVpbmVyQGdtYWlsLmNvbSIsInVzZXJSb2xlIjoidHJhaW5lciIsIm5hbWUiOiJWYW55YSBUcmVpbmVyIiwiaWF0IjoxNzAxMTYwMzExLCJleHAiOjE3MDExNjEyMTF9.G5Fp6xatq7_ceq02hMCmW5aIMgbDVL26kzM7sbQ4kVg


###