# Create a new user
POST http://localhost:3333/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "userName": "Василий",
  "userMail": "cliendddt@gmail.cwm",
  "userAvatar": "",
  "password": "adsfaasdfadf",
  "userGender": "мужской",
  "birthDate": "1955-11-06",
  "userRole": "client",
  "description": "trainertrainertrainertrainertrainer",
  "location": "Пионерская",
  "backgraundPicture": "asdf.jpg",
  "trainerBody": {
    "sertificates": ["sert.pdf"],
    "merit": "чтото напишем",
    "readinessForPrivate": true
  },
  "levelOfExperience": "профессионал",
  "typesOfTraining": ["стрейчинг", "кроссфит"]
}
###

# Update user 
PATCH http://localhost:3333/api/auth/update HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMyLCJlbWFpbCI6InZhc3lhMzNUcmVpbmVyQG1haWwuY29tIiwidXNlclJvbGUiOiJ0cmFpbmVyIiwibmFtZSI6ImFzZGZhZGYxIiwiaWF0IjoxNjkxNTYyNjY3LCJleHAiOjE2OTE1NjM1Njd9.Li3az6tbwDnNFT4wXQtW7UOXcty1DRRXI1SASdI1mfY
Content-Type: application/json

{
  "userName": "Васил1www111ий",
  "userAvatar": ""
}

###

# Get user by ID
GET http://localhost:3333/api/auth/user/51 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUxLCJlbWFpbCI6ImNsaWVudEBnbWFpbC5jd20iLCJ1c2VyUm9sZSI6InRyYWluZXIiLCJuYW1lIjoi0JLQsNGB0LjQu9C40LkiLCJpYXQiOjE2OTE3NjQ1NTMsImV4cCI6MTY5MTc2NTQ1M30.KltWNsBpTlmjFYL_L14sgH0rkR6dEDHAcvWpJEwCx0w
###

# Login user by email and password
POST http://localhost:3333/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "client@gmail.cwm",
  "password": "adsfaasdfadf"
}
###
# Get user  feed
GET http://localhost:3333/api/auth/feed?limit=4&page=1&userRole=trainer&locations=Пионерская,Петроградская&typesOfTraining=йога,кроссфит HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJlbWFpbCI6InNlcDRvb2NsaWVudGllbnFxMjMyM292QGdtYWlsLmN3bSIsInVzZXJSb2xlIjoidHJhaW5lciIsIm5hbWUiOiLQktCw0YHQuNC70LjQuSIsImlhdCI6MTY5MDk5NTQ5NCwiZXhwIjoxNjkwOTk2Mzk0fQ.iY9A0_SuParyBJfRt3EFe9YMCp8HLdqvaE-iqheleLA
###
# Get new JWT pair
POST http://localhost:3333/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJlbWFpbCI6InNlcDRvb2NsaWVudGllbnFxMjMyM292QGdtYWlsLmN3bSIsInVzZXJSb2xlIjoidHJhaW5lciIsIm5hbWUiOiLQktCw0YHQuNC70LjQuSIsInRva2VuSWQiOiJlYjk4Yzg1Ni05YzQxLTQxNWMtODNiYy01ZDIyOTZjYWIyNzEiLCJpYXQiOjE2OTA5OTU0OTQsImV4cCI6MTY5MzU4NzQ5NH0.6RFI5wGNDmjGm7QwaimEskqhvDqRGnpnUpaOqSTIReI


###

# Check user token
GET http://localhost:3333/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUxLCJlbWFpbCI6ImNsaWVudEBnbWFpbC5jd20iLCJ1c2VyUm9sZSI6ImNsaWVudCIsIm5hbWUiOiLQktCw0YHQuNC70LjQuSIsImlhdCI6MTY5MTY4NDYxOSwiZXhwIjoxNjkxNjg1NTE5fQ.ZBPW8iiWPFWOg45OhBFo69GKVMJBQszSnl5O0MCaaZk


###