# Create a new training
POST http://localhost:3333/api/training/register HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE5LCJlbWFpbCI6ImNsaWVudEBnbWFpbC5jd20iLCJ1c2VyUm9sZSI6ImNsaWVudCIsIm5hbWUiOiLQktCw0YHQuNC70LjQuSIsImlhdCI6MTY4OTc4NzQ1MSwiZXhwIjoxNjg5Nzg4MzUxfQ.OybmMb_p8vo4MaPEkjblCu0m8JQmRijR4uK0_pr4QvE
Content-Type: application/json

{
  "title": "Бfкс с Кличко",
  "backgroundPicture":"" ,
  "levelOfUser": "новичок",
  "typeOfTraining": "бег",
  "duration": "10-30 мин",
  "price": 5,
  "caloriesQtt": 1000,
  "description": "description must be longer than or equal to 10 characters",
  "trainingGender": "для мужчин",
  "video": "",
  "rating": 3,
  "trainerId": 5,
  "isPromo": false
}
###

# Update training information by ID

PATCH  http://localhost:3333/api/training/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJlbWFpbCI6InNlcDNvb2NsaWVudGFsdHJhaW5lcmllbnFxMjMyM292QGdtYWlsLmN3bSIsInVzZXJSb2xlIjoidHJhaW5lciIsIm5hbWUiOiLQktCw0YHQuNC70LjQuSIsImlhdCI6MTY4OTA1NzI1OCwiZXhwIjoxNjg5MDU4MTU4fQ.YT9d1vd8nNdGsz7-Ch7GjipgJgIixfSHimC4lmE13yI
Content-Type: application/json

{
  "title": "Бiксi с Кличко",
  "rating": 7
}
###

#Get training information by ID

GET http://localhost:3333/api/training/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJlbWFpbCI6InNlcDNvb2NsaWVudGFsdHJhaW5lcmllbnFxMjMyM292QGdtYWlsLmN3bSIsInVzZXJSb2xlIjoidHJhaW5lciIsIm5hbWUiOiLQktCw0YHQuNC70LjQuSIsImlhdCI6MTY4OTA1NzI1OCwiZXhwIjoxNjg5MDU4MTU4fQ.YT9d1vd8nNdGsz7-Ch7GjipgJgIixfSHimC4lmE13yI
###

# Get training feed

GET  http://localhost:3333/api/training/feed?durations=10-30%20мин&priceMin=1&priceMax=12&caloriesQttMin=1000&caloriesQttMax=2000 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE4LCJlbWFpbCI6InRyYWluZXJAZ21haWwuY3dtIiwidXNlclJvbGUiOiJ0cmFpbmVyIiwibmFtZSI6ItCS0LDRgdC40LvQuNC5IiwiaWF0IjoxNjg5Nzg3NjU3LCJleHAiOjE2ODk3ODg1NTd9.pADKvcVIdHU32bGVICkzqy5h0ALL4rlLOGTOicHGVVA


####

GET  http://localhost:3333/api/training/feed?durations=10-30%20мин&priceMin=1&priceMax=12&caloriesQttMin=1000&caloriesQttMax=2000 HTTP/1.1